language: node_js
node_js: "10.15"
cache: yarn

_production-env: &production-env
  ENVIRONMENT: production
  RANCHER_CLUSTERID: c-gxsr7

_production-job: &production-job
  stage: production
  name: SITE_NAME
  script: npx @base-cms/website-deployment-tool deploy SITE_NAME SITE_STACK
  install: skip
  env:
    <<: *production-env

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env:
        NODE_ENV: test

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env:
        <<: *production-env

    ##########################
    # vvv ADD SITES HERE vvv #
    ##########################

    - <<: *production-job
      name: aviationpros.com
      script: npx @base-cms/website-deployment-tool deploy aviationpros.com picon

    - <<: *production-job
      name: bioopticsworld.com
      script: npx @base-cms/website-deployment-tool deploy bioopticsworld.com aerilon

    - <<: *production-job
      name: broadbandtechreport.com
      script: npx @base-cms/website-deployment-tool deploy broadbandtechreport.com aerilon

    - <<: *production-job
      name: cablinginstall.com
      script: npx @base-cms/website-deployment-tool deploy cablinginstall.com aerilon

    - <<: *production-job
      name: cpapracticeadvisor.com
      script: npx @base-cms/website-deployment-tool deploy cpapracticeadvisor.com picon

    - <<: *production-job
      name: dentaleconomics.com
      script: npx @base-cms/website-deployment-tool deploy dentaleconomics.com aerilon

    - <<: *production-job
      name: dentistryiq.com
      script: npx @base-cms/website-deployment-tool deploy dentistryiq.com aerilon

    - <<: *production-job
      name: distributedenergy.com
      script: npx @base-cms/website-deployment-tool deploy distributedenergy.com picon

    - <<: *production-job
      name: evaluationengineering.com
      script: npx @base-cms/website-deployment-tool deploy evaluationengineering.com picon

    - <<: *production-job
      name: firehouse.com
      script: npx @base-cms/website-deployment-tool deploy firehouse.com picon

    - <<: *production-job
      name: piprocessinstrumentation.com
      script: npx @base-cms/website-deployment-tool deploy piprocessinstrumentation.com picon

    - <<: *production-job
      name: foresternetwork.com
      script: npx @base-cms/website-deployment-tool deploy foresternetwork.com picon

    - <<: *production-job
      name: gxcontractor.com
      script: npx @base-cms/website-deployment-tool deploy gxcontractor.com picon

    - <<: *production-job
      name: hcinnovationgroup.com
      script: npx @base-cms/website-deployment-tool deploy hcinnovationgroup.com picon

    - <<: *production-job
      name: hpnonline.com
      script: npx @base-cms/website-deployment-tool deploy hpnonline.com picon

    - <<: *production-job
      name: industrial-lasers.com
      script: npx @base-cms/website-deployment-tool deploy industrial-lasers.com aerilon

    - <<: *production-job
      name: intelligent-aerospace.com
      script: npx @base-cms/website-deployment-tool deploy intelligent-aerospace.com aerilon

    - <<: *production-job
      name: laserfocusworld.com
      script: npx @base-cms/website-deployment-tool deploy laserfocusworld.com aerilon

    - <<: *production-job
      name: ledsmagazine.com
      script: npx @base-cms/website-deployment-tool deploy ledsmagazine.com aerilon

    - <<: *production-job
      name: lightwaveonline.com
      script: npx @base-cms/website-deployment-tool deploy lightwaveonline.com aerilon

    - <<: *production-job
      name: locksmithledger.com
      script: npx @base-cms/website-deployment-tool deploy locksmithledger.com picon

    - <<: *production-job
      name: masstransitmag.com
      script: npx @base-cms/website-deployment-tool deploy masstransitmag.com picon

    - <<: *production-job
      name: militaryaerospace.com
      script: npx @base-cms/website-deployment-tool deploy militaryaerospace.com aerilon

    - <<: *production-job
      name: mlo-online.com
      script: npx @base-cms/website-deployment-tool deploy mlo-online.com picon

    - <<: *production-job
      name: mswmanagement.com
      script: npx @base-cms/website-deployment-tool deploy mswmanagement.com picon

    - <<: *production-job
      name: officer.com
      script: npx @base-cms/website-deployment-tool deploy officer.com picon

    - <<: *production-job
      name: offshore-mag.com
      script: npx @base-cms/website-deployment-tool deploy offshore-mag.com aerilon

    - <<: *production-job
      name: perioimplantadvisory.com
      script: npx @base-cms/website-deployment-tool deploy perioimplantadvisory.com aerilon

    - <<: *production-job
      name: plasticsmachinerymanufacturing.com
      script: npx @base-cms/website-deployment-tool deploy plasticsmachinerymanufacturing.com picon

    - <<: *production-job
      name: processingmagazine.com
      script: npx @base-cms/website-deployment-tool deploy processingmagazine.com picon

    - <<: *production-job
      name: rdhmag.com
      script: npx @base-cms/website-deployment-tool deploy rdhmag.com aerilon

    - <<: *production-job
      name: securityinfowatch.com
      script: npx @base-cms/website-deployment-tool deploy securityinfowatch.com picon

    - <<: *production-job
      name: stormh2o.com
      script: npx @base-cms/website-deployment-tool deploy stormh2o.com picon

    - <<: *production-job
      name: strategies-u.com
      script: npx @base-cms/website-deployment-tool deploy strategies-u.com aerilon

    - <<: *production-job
      name: taxpracticeadvisor.com
      script: npx @base-cms/website-deployment-tool deploy taxpracticeadvisor.com picon

    - <<: *production-job
      name: utilityproducts.com
      script: npx @base-cms/website-deployment-tool deploy utilityproducts.com aerilon

    - <<: *production-job
      name: vehicleservicepros.com
      script: npx @base-cms/website-deployment-tool deploy vehicleservicepros.com picon

    - <<: *production-job
      name: vendingmarketwatch.com
      script: npx @base-cms/website-deployment-tool deploy vendingmarketwatch.com picon

    - <<: *production-job
      name: vision-systems.com
      script: npx @base-cms/website-deployment-tool deploy vision-systems.com aerilon

    - <<: *production-job
      name: watertechonline.com
      script: npx @base-cms/website-deployment-tool deploy watertechonline.com aerilon

    - <<: *production-job
      name: waterworld.com
      script: npx @base-cms/website-deployment-tool deploy waterworld.com aerilon


    ##########################
    # ^^^ ADD SITES HERE ^^^ #
    ##########################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env:
        <<: *production-env
